config/routes.rb
Rails.application.routes.draw do
  root to: 'chore_assignments#index'
  
  resource :session, only: :new
  
  resources :chores

  get "/users/leaderboard", to: "users#leaderboard", as: "leaderboard"
  post "/users/remove_resident/:id", to: "users#remove_resident", as: "remove_resident"
  post "/users/add_resident/:id", to: "users#add_resident", as: "add_resident"
  resources :users, only: [:show, :index]

  get "/auth/github/callback", to: "sessions#create"
  delete "/signout", to: "sessions#destroy", as: "signout"
  
  post "/chore_assignments/send_chores", to: "chore_assignments#send_chores", as: "send_chores"
  get "/chore_assignments/complete/:id", to: "chore_assignments#complete", as: "complete_chore"
  get "/chore_assignments/flag/:id", to: "chore_assignments#flag", as: "flag_chore"
  get "/chore_assignments/unflag/:id", to: "chore_assignments#unflag", as: "unflag_chore"

  get "/static_pages/thank_you", to: "static_pages#thank_you", as: "thank_you"
  get "/static_pages/too_early", to: "static_pages#too_early", as: "too_early"
end

app/models/chore_assignment.rb
# == Schema Information
#
# Table name: chore_assignments
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  chore_id   :integer          not null
#  due_date   :date             not null
#  created_at :datetime
#  updated_at :datetime
#  completed  :boolean          default(FALSE)
#  flagged    :boolean          default(FALSE)
#

class ChoreAssignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :chore

  def self.send_chores!
    new_assignments = Chore.assign_chores!(User.where(current_resident: true).map(&:id))
    new_assignments.each do |assignment|
      Notifier.chore_notification_email(assignment).deliver
    end
  end

  def self.send_overdue!
    self.where(due_date: Date.yesterday).each do |assignment|
      Notifier.overdue_email(assignment).deliver if assignment.overdue?
    end
  end

  def overdue?
    self.due_date < Date.today && !self.completed
  end
end

app/controllers/chore_assignments_controller.rb
class ChoreAssignmentsController < ApplicationController
  before_action :ensure_current_user
  def index
    @chore_assignments = ChoreAssignment.includes(:chore, :user).where(
          due_date: Chronic.parse('last Saturday')..Chronic.parse('next Sunday')
          ).sort_by { |assignment| assignment.due_date }
  end

  def complete
    @chore_assignment = ChoreAssignment.find(params[:id])
    if @chore_assignment.due_date < Date.tomorrow
      @chore_assignment.completed = true
      @chore_assignment.save
      redirect_to thank_you_url
    else
      redirect_to too_early_url
    end
  end

  def flag
    @chore_assignment = ChoreAssignment.find(params[:id])
    @chore_assignment.flagged = true
    @chore_assignment.save
    redirect_to root_url
  end

  def unflag
    @chore_assignment = ChoreAssignment.find(params[:id])
    @chore_assignment.flagged = false
    @chore_assignment.save
    redirect_to root_url
  end

  def send_chores
    ChoreAssignment.send_chores!
    redirect_to root_url
  end

  def send_overdue
    ChoreAssignment.send_overdue!
    redirect_to root_url
  end
end

app/helpers/chore_assignments_helper.rb
module ChoreAssignmentsHelper
end

app/views/chore_assignments/_assignment.html.erb
<div class="chore-assignment pull-left <%= status %>">
  <h5><%= assignment.chore.title %></h5>
    <%= image_tag(assignment.user.photo, class: "user-photo img-responsive center-block") %>
  <div class="clearfix"></div>
  <p>
    <%=link_to assignment.user.name, user_url(assignment.user) %>
  </p>
  <p>Due: <%= assignment.due_date.to_formatted_s(:long_ordinal) %></p>
  <p>
    <% if (current_user == assignment.user || current_user.admin) && !assignment.completed %>
      <%= link_to "mark completed", complete_chore_url(assignment) %>
    <% elsif assignment.flagged && current_user.admin %>
      <%= link_to "un-flag", unflag_chore_url(assignment) %>
    <% elsif assignment.completed && current_user != assignment.user && !assignment.flagged %>
      <%= link_to "flag", flag_chore_url(assignment) %>
    <% end %>
  </p>
  <% if assignment.flagged%>
    <p>Flagged</p>
  <% elsif assignment.completed %>
    <p>Completed!</p>
  <% elsif assignment.overdue? %>
    <p>Overdue</p>
  <% else %>
    <p>Not yet completed.</p>
  <% end %>
</div>

app/views/chore_assignments/_day.html.erb
<div class="row">
  <div class="col-sm-12">
    <h3><%= weekday %></h3>
    <% @chore_assignments.select { |asgn| asgn.chore.day == weekday }.sort.each do |asgn| %>
      <% if asgn.completed %>
        <% status = 'completed' %>
      <% else %>
        <% status = asgn.overdue? ? 'overdue' : 'incomplete' %>
      <% end %>
      <% status += ' flagged' if asgn.flagged %>      
      <%= render partial: 'chore_assignments/assignment', 
                 locals: { assignment: asgn, status: status } %>
    <% end %>
  </div>
</div>

app/views/chore_assignments/index.html.erb
<h1>Chores!</h1>

<% if current_user.admin %>
  <div class="row">
    <div class="col-sm-12">
      <label>Click here to email everyone their chores:
        <%= button_to "Assign Chores!", send_chores_url, method: :post, class: "btn btn-lg btn-success"%>
      </label>
    </div>
  </div>
<% end %>


<% ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"].each do |weekday| %>
  <%= render partial: 'chore_assignments/day', locals: { weekday: weekday } %>
  <hr>
<% end %>