config/routes.rb
Rails.application.routes.draw do
  root to: 'chore_assignments#index'
  
  resource :session, only: :new
  
  resources :chores

  get "/users/leaderboard", to: "users#leaderboard", as: "leaderboard"
  post "/users/remove_resident/:id", to: "users#remove_resident", as: "remove_resident"
  post "/users/add_resident/:id", to: "users#add_resident", as: "add_resident"
  resources :users, only: [:show, :index]

  get "/auth/github/callback", to: "sessions#create"
  delete "/signout", to: "sessions#destroy", as: "signout"
  
  post "/chore_assignments/send_chores", to: "chore_assignments#send_chores", as: "send_chores"
  get "/chore_assignments/complete/:id", to: "chore_assignments#complete", as: "complete_chore"
  get "/chore_assignments/flag/:id", to: "chore_assignments#flag", as: "flag_chore"
  get "/chore_assignments/unflag/:id", to: "chore_assignments#unflag", as: "unflag_chore"

  get "/static_pages/thank_you", to: "static_pages#thank_you", as: "thank_you"
  get "/static_pages/too_early", to: "static_pages#too_early", as: "too_early"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  name             :string(255)      not null
#  uid              :string(255)      not null
#  email            :string(255)      not null
#  photo            :string(255)      not null
#  created_at       :datetime
#  updated_at       :datetime
#  admin            :boolean          default(FALSE), not null
#  current_resident :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  validates :name, :uid, :email, :photo, presence: true
  validates :uid, uniqueness: true

  has_many :chore_assignments, dependent: :destroy
  has_many :assigned_chores, through: :chore_assignments, source: :chore

  def self.create_with_omniauth(auth)
    create! do |user|
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.photo = auth["info"]["image"]
      user.email = auth["info"]["email"]
    end
  end

  def self.current_residents
    User.where(current_resident: true).includes(:chore_assignments)
  end

  def completed_chores
    @completed_chores ||= self.chore_assignments.where(completed: true, flagged: false)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def index
    @residents = User.where(current_resident: true)
    if current_user.admin
      @all_users = User.all.sort_by { |user| user.created_at }
    end
  end

  def leaderboard
    @users = User.current_residents.sort_by { |user| -user.completed_chores.count }
  end

  def add_resident
    @user = User.find(params[:id])
    @user.current_resident = true
    @user.save
    redirect_to users_url
  end

  def remove_resident
    @user = User.find(params[:id])
    @user.current_resident = false
    @user.save
    redirect_to users_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>App Academy Residents</h1>

<ul class="users">
  <% @residents.each do |user| %>
    
    <li class="text-center">
      <a href="<%= user_url(user.id) %>">
        <%= image_tag(user.photo) %> <br>
        <%= user.name %>
      </a>
      <% if user.admin %>
        (Admin)
      <% end %>
      <% if current_user.admin %>
        <br>
        <%= button_to "remove from residents list", remove_resident_url(user), method: :post, class: "btn btn-link" %>
      <% end %>
    </li>
    
  <% end %>
</ul>

<% if current_user.admin %>
  <h1>All Users</h1>
  <ul class="users">
    <% @all_users.each do |user| %>
      <li class="text-center">
        <a href="<%= user_url(user.id) %>">
          <%= image_tag(user.photo) %> <br>
          <%= user.name %>
        </a>
        <% if user.admin %>
          (Admin)
        <% end %>
        <% if current_user.admin && !user.current_resident %>
          <br>
          <%= link_to "add to residents list", add_resident_url(user), method: :post, class: "btn btn-link" %>
        <% end %>
      </li>
    
  <% end %>
  </ul>
<% end %>

app/views/users/leaderboard.html.erb
<h1>Current Chore Leaders:</h1>
<ul id="leader-list">
  <% @users.each do |user| %>
    
    <li>
      <a href="<%= user_url(user.id) %>" data-toggle="tooltip" data-placement="top" title="<%= user.completed_chores.count %> chores completed!" class="leader-photo">
        <%= image_tag(user.photo) %>
        <%= user.name %>
      </a><br>
      <% user.completed_chores.count.times do %>
        <div class="chore-square"></div>
      <% end %>
    </li>
    
  <% end %>
</ul>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Chore History:</h1>

<div class="row">
  <div class="col-sm-12">
    <div id="current">
      <h3>Chores This Week:</h3>
      <br>
      <% @user.chore_assignments.each do |assignment| %>
        <% if assignment.due_date >= Date.today %>
          <% status = assignment.completed ? 'completed' : 'incomplete' %>      
          <% status+=' flagged' if assignment.flagged %>
          <%= render partial: 'chore_assignments/assignment', 
                     locals: { assignment: assignment, status: status } %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div id="past">
      <h3>Chore History:</h3>
      <br>
      <% @user.chore_assignments.each do |assignment| %>
        <% if assignment.due_date < Date.today %>
            <% status = assignment.completed ? 'completed' : 'overdue' %>
            <% status += ' flagged' if assignment.flagged %>
            <%= render partial: 'chore_assignments/assignment', 
                       locals: { assignment: assignment, status: status } %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>