config/routes.rb
Rails.application.routes.draw do
  root to: 'chore_assignments#index'
  
  resource :session, only: :new
  
  resources :chores

  get "/users/leaderboard", to: "users#leaderboard", as: "leaderboard"
  post "/users/remove_resident/:id", to: "users#remove_resident", as: "remove_resident"
  post "/users/add_resident/:id", to: "users#add_resident", as: "add_resident"
  resources :users, only: [:show, :index]

  get "/auth/github/callback", to: "sessions#create"
  delete "/signout", to: "sessions#destroy", as: "signout"
  
  post "/chore_assignments/send_chores", to: "chore_assignments#send_chores", as: "send_chores"
  get "/chore_assignments/complete/:id", to: "chore_assignments#complete", as: "complete_chore"
  get "/chore_assignments/flag/:id", to: "chore_assignments#flag", as: "flag_chore"
  get "/chore_assignments/unflag/:id", to: "chore_assignments#unflag", as: "unflag_chore"

  get "/static_pages/thank_you", to: "static_pages#thank_you", as: "thank_you"
  get "/static_pages/too_early", to: "static_pages#too_early", as: "too_early"
end

app/views/shared/_addChore.html.erb
<div class="col-sm-8">
  <div id="choreform">
    <form action="<%= action %>" method="post">
      <%= form_auth_token %>
      <% if chore.persisted? %>
        <input type='hidden' name='_method' value="patch">
      <% end %>
      <label>Title:</br>
        <input type="text" class="form-control" name="chore[title]" value="<%= chore.title %>">
      </label><br>
    
      <label>Day of the Week:</br>
        <select class="form-control" name="chore[day]">
        <% ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"].each do |weekday| %>
          <option value="<%= weekday %>" <%= 'selected' if chore.day == weekday %>><%= weekday %></option>
        <% end %>
        </select>
      </label>

      <label>Number of People:<br>
        <input type="number" class="form-control" name="chore[crew]" value="<%= chore.crew %>">
      </label><br>

      <label>Description
        <textarea name="chore[description" class="form-control" cols="30" rows="10"><%= chore.description %></textarea>
      </label><br>
    
      <% if chore.persisted? %>
        <input type="submit" value="Update Chore" class="btn btn-primary">
      <% else %>
        <input type="submit" value="Add Chore" class="btn btn-primary">
      <% end %>
    </form>
  </div>
</div>

app/views/shared/_nav.html.erb
<% if current_user %>
<div class="nav navbar navbar-inverse">
  <a class="navbar-brand" href="<%= root_url %>">Choreroom Private Beta</a>
  <ul class="nav navbar-nav navbar-left">
    <li><a href="<%= user_url(current_user.id) %>">Hello, <%= current_user.name %>!</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Chores<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="<%= root_url %>">Current Chore Assignments</a></li>
          <li><a href="<%= chores_url %>">View All Chores</a></li>
          <% if current_user.admin %>
            <li><a href="<%= new_chore_url %>">Add New Chore</a></li>
          <% end %>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Residents<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="<%= users_url %>">Residents List</a></li>
          <li><a href="<%= leaderboard_url %>">Leaderboard</a></li>
        </ul>
      </li>
  </ul>
  <ul class="nav navbar-nav pull-right">
    <li><%= button_to "Sign out", signout_url, method: :delete, class: "btn btn-warning navbar-btn" %></li>
  </ul>
</div>
<% end %>