config/routes.rb
Rails.application.routes.draw do
  root to: 'chore_assignments#index'
  
  resource :session, only: :new
  
  resources :chores

  get "/users/leaderboard", to: "users#leaderboard", as: "leaderboard"
  post "/users/remove_resident/:id", to: "users#remove_resident", as: "remove_resident"
  post "/users/add_resident/:id", to: "users#add_resident", as: "add_resident"
  resources :users, only: [:show, :index]

  get "/auth/github/callback", to: "sessions#create"
  delete "/signout", to: "sessions#destroy", as: "signout"
  
  post "/chore_assignments/send_chores", to: "chore_assignments#send_chores", as: "send_chores"
  get "/chore_assignments/complete/:id", to: "chore_assignments#complete", as: "complete_chore"
  get "/chore_assignments/flag/:id", to: "chore_assignments#flag", as: "flag_chore"
  get "/chore_assignments/unflag/:id", to: "chore_assignments#unflag", as: "unflag_chore"

  get "/static_pages/thank_you", to: "static_pages#thank_you", as: "thank_you"
  get "/static_pages/too_early", to: "static_pages#too_early", as: "too_early"
end

app/models/chore.rb
# == Schema Information
#
# Table name: chores
#
#  id          :integer          not null, primary key
#  title       :string(255)      not null
#  created_at  :datetime
#  updated_at  :datetime
#  day         :string(255)
#  crew        :integer          not null
#  description :text
#

class Chore < ActiveRecord::Base
  validates :title, :day, :crew, presence: true
  
  has_many :chore_assignments, dependent: :destroy
  has_many :users, through: :chore_assignments, source: :user

  def self.assign_chores!(user_ids)
    total_assignments = Chore.all.map(&:crew).reduce(:+)
    user_list = user_ids.shuffle!
    user_list += user_list.shuffle! until user_list.length >= total_assignments
    new_assignments = []
    self.all.each do |chore|
      chore.current_assignments.each(&:destroy)
      chore.crew.times do 
        new_assignments << ChoreAssignment.create({
          chore_id: chore.id, 
          user_id: user_list.shift, 
          due_date: Chronic.parse("#{chore.day}")})
      end
    end
    new_assignments
  end

  def current_assignments
    self.chore_assignments.where(completed: false).reject { |asgn| asgn.overdue? }
  end
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :ensure_current_user
  before_action :ensure_admin, except: :index

  def index
    @chores = Chore.all.sort_by { |chore| chore.day }
  end


  def new
    @chore = Chore.new
  end

  def create
    @chore = Chore.new(chore_params)
    if @chore.save
      flash[:notice] = "#{@chore.title} added!"
      redirect_to chores_url
    else
      flash[:errors] = @chore.errors.full_messages
      redirect_to chores_url
    end
  end

  def edit
    @chore = Chore.find(params[:id])
  end

  def update
    @chore = Chore.find(params[:id])
    @chore.update_attributes(chore_params)
    redirect_to chores_url
  end

  def destroy
    @chore = Chore.find(params[:id])
    @chore.try(:destroy)
    flash[:notice] = "#{@chore.title} deleted!"
    redirect_to chores_url
  end

  private
  def chore_params
    params.require(:chore).permit(:title, :day, :crew, :description)
  end

  def ensure_admin
    unless current_user.admin
      flash[:errors] = ["Only admins can create and edit chores."]
      redirect_to :back
    end
  end
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/views/chores/edit.html.erb
<h1>Edit <%= @chore.title %></h1>
<p><%= button_to "Delete Chore", chore_url(@chore), method: :delete, class: "btn btn-danger" %> Warning! This can't be undone!</p>
<%= render partial: 'shared/addChore',
           locals: { action: chore_url(@chore), chore: @chore } %>

app/views/chores/index.html.erb
<h1>Chore all the Things!</h1>
<p><%= button_to 'Add New Chore', new_chore_url, class: "btn btn-primary", method: :get %></p>
<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Weekday</th>
      <th>Number of People</th>
    </tr>
  </thead>
  <% @chores.sort.each do |chore| %>
  <tr>
    <% if current_user.admin %>
      <td><%= link_to chore.title, edit_chore_url(chore) %></td>
    <% else %>
      <td><%= chore.title %></td>
    <% end %>
    <td><%= chore.description %></td>
    <td><%= chore.day %></td>
    <td><%= chore.crew %></td>
  </tr>
  <% end %>

</table>

app/views/chores/new.html.erb
<h1>Add New Chore</h1>
<%= render partial: 'shared/addChore',
           locals: { action: chores_url, chore: @chore } %>